# Generated by Django 3.2.5 on 2023-10-21 20:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0015_institution_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='data_sources')),
                ('dirty', models.BooleanField(default=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('BASE', 'Base'), ('VALUE_COUNTS', 'Value counts')], default='BASE', max_length=12)),
                ('keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('aggregation', models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Avg'), ('COUNT', 'Count'), ('NOTNAN', 'NotNan')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='data_views')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reports.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('IN_PROGRESS', 'In progress'), ('READY', 'Joined')], default='EMPTY', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ReportComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('TABLE', 'Table'), ('BAR_PLOT', 'Bar plot'), ('HEADER', 'Header'), ('HTML', 'HTML'), ('MAP_FREQUENCY', 'MAP_FREQUENCY')], default='TABLE', max_length=30)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='DataComponent',
            fields=[
                ('reportcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportcomponent')),
                ('data_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_components', to='reports.dataview')),
            ],
            bases=('reports.reportcomponent',),
        ),
        migrations.CreateModel(
            name='HeaderComponent',
            fields=[
                ('reportcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportcomponent')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=512)),
            ],
            bases=('reports.reportcomponent',),
        ),
        migrations.CreateModel(
            name='HTMLComponent',
            fields=[
                ('reportcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportcomponent')),
                ('text', models.TextField()),
            ],
            bases=('reports.reportcomponent',),
        ),
        migrations.CreateModel(
            name='ValueCountsView',
            fields=[
                ('dataview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.dataview')),
                ('threshold', models.IntegerField(default=0)),
            ],
            bases=('reports.dataview',),
        ),
        migrations.CreateModel(
            name='BarPlotComponent',
            fields=[
                ('datacomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.datacomponent')),
                ('title', models.CharField(max_length=256)),
                ('index', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
            bases=('reports.datacomponent',),
        ),
        migrations.CreateModel(
            name='TableComponent',
            fields=[
                ('datacomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.datacomponent')),
                ('title', models.CharField(max_length=256)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
            ],
            bases=('reports.datacomponent',),
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('file', models.FileField(upload_to='file_reports')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_reports', to='reports.datasource')),
            ],
            bases=('reports.report',),
        ),
    ]
