# Generated by Django 3.2.5 on 2022-10-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0005_auto_20221001_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('CAMPAIGN', 'Campaign'), ('JOINED', 'Joined')], default='CAMPAIGN', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.datasource')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            bases=('reports.datasource',),
        ),
    ]
