# Generated by Django 3.2.5 on 2022-10-02 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('IN_PROGRESS', 'In progress'), ('READY', 'Joined')], default='EMPTY', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('file', models.FileField(upload_to='file_reports')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_reports', to='reports.campaigndatasource')),
            ],
            bases=('reports.report',),
        ),
    ]
