# Generated by Django 3.2.5 on 2023-10-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFrequencyComponent',
            fields=[
                ('datacomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.datacomponent')),
                ('title', models.CharField(max_length=256)),
                ('index', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
            bases=('reports.datacomponent',),
        ),
    ]
