# Generated by Django 3.2.5 on 2023-11-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_mapfrequencycomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='include_all_institutions',
            field=models.BooleanField(default=True),
        ),
    ]
