# Generated by Django 3.2.5 on 2023-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_datasource_include_all_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='layout',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='FileReport',
        ),
    ]
