# Generated by Django 3.2.5 on 2023-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20231125_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='layout',
            field=models.JSONField(default=dict),
        ),
    ]
