# Generated by Django 3.2.5 on 2023-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_layout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcomponent',
            unique_together={('name', 'report')},
        ),
    ]
