# Generated by Django 3.2.5 on 2024-01-01 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_reportcomponent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataview',
            name='keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='dataview',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None),
        ),
    ]
