# Generated by Django 3.2.5 on 2024-01-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20240101_2259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcomponent',
            unique_together=set(),
        ),
    ]
