# Generated by Django 3.2.5 on 2024-04-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_reportcomponent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesComponent',
            fields=[
                ('reportcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportcomponent')),
            ],
            bases=('reports.reportcomponent',),
        ),
        migrations.AddField(
            model_name='reportcomponent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reportcomponent',
            name='type',
            field=models.CharField(choices=[('TABLE', 'Table'), ('BAR_PLOT', 'Bar plot'), ('HEADER', 'Header'), ('HTML', 'HTML'), ('MAP_FREQUENCY', 'Map frequency'), ('REFERENCES', 'References')], default='TABLE', max_length=30),
        ),
    ]
