# Generated by Django 3.2.5 on 2024-04-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_institution_metadata'),
        ('reports', '0009_auto_20240402_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='campaigns.campaign'),
        ),
    ]
