# Generated by Django 3.2.5 on 2024-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_datasource_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomponent',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tablecomponent',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
