# Generated by Django 3.2.5 on 2022-01-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
