# Generated by Django 3.2.5 on 2022-06-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_documentquery_accepted_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('PERSON', 'Person'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='link',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='campaigns.institutiongroup'),
            preserve_default=False,
        ),
    ]
