# Generated by Django 3.2.5 on 2022-08-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20220619_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiongroup',
            name='type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('PERSON', 'Person'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], default=None, max_length=12),
        ),
    ]
