# Generated by Django 3.2.5 on 2022-10-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20221001_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiongroup',
            name='type',
        ),
        migrations.AddField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='campaigns.institution'),
        ),
        migrations.AddField(
            model_name='institutiongroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='campaigns.institutiongroup'),
        ),
    ]
