# Generated by Django 3.2.5 on 2022-10-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20221011_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='main_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
