# Generated by Django 3.2.5 on 2022-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished')], default='CREATED', max_length=12),
        ),
    ]
