# Generated by Django 3.2.5 on 2023-03-26 19:19

import campaigns.models.institutions.consts
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_filesource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutiongroup',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('link', 'Link'), ('address', 'Address')], max_length=32), blank=True, default=campaigns.models.institutions.consts.get_default_institution_fields, size=None),
        ),
    ]
