# Generated by Django 3.2.5 on 2023-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_institutiongroup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
