# Generated by Django 3.2.5 on 2023-06-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20230326_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='raw_report',
            field=models.JSONField(default={}),
        ),
    ]
